import type { Metadata } from 'next'

import { Inter, Raleway, Bitter } from 'next/font/google'
import { Playfair_Display } from 'next/font/google'
import {} from 'next/font/google'
import './globals.css'
import Image from 'next/image'
import NavLinks from '../components/NavLinks'

import { Providers } from '../contexts/providers'
import { NextUIProvider } from '@nextui-org/react'
import GlobalNavBar from '../components/GlobalNavBar'
import Header from '../components/Header'
import Sidebar from '@/components/ui/Sidebar'
const inter = Inter({ subsets: ['latin'] })
const raleway = Raleway({ subsets: ['latin'] })
const playfair = Playfair_Display({
  subsets: ['latin'],
  weight: ['400', '700'],
})
const bitter = Bitter({
  subsets: ['latin'],
  weight: ['100', '200', '300', '500'],
})

export const metadata: Metadata = {
  title: {
    template: 'Photo',
    default: 'Photo attempt',
  },

  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html className="" lang="en">
      <body className={`${bitter.className} h-screen flex flex-col`}>
        <div className="lg:hidden">
          <GlobalNavBar />
        </div>
        {/* <Header /> */}
        <div className="flex-1 flex overflow-hidden ">
          <div className="lg:block hidden">
            <Sidebar />
          </div>
          <main className="flex-1 overflow-auto p-4">
            <Providers>{children}</Providers>
          </main>
        </div>
      </body>
    </html>
  )
}
