import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NavLinks from './components/NavLinks'

import { Providers } from './contexts/providers'
import { NextUIProvider } from '@nextui-org/react'
import GlobalNavBar from './components/GlobalNavBar'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Photo attempt',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <GlobalNavBar /> */}

        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
