import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NavLinks from './components/NavLinks'
import { ApolloWrapper } from './contexts/ApolloWrapper'
import { Providers } from './contexts/providers'
import { NextUIProvider } from '@nextui-org/react'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Photo attempt',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <p>This is a global navbar</p>
          <NavLinks />
        </nav>
        <ApolloWrapper>
          <NextUIProvider>{children}</NextUIProvider>
        </ApolloWrapper>
      </body>
    </html>
  )
}
